#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Piotr Lewandowski

# Short bio or description (displayed in the header)
description: Getting Things Programmed - Notes

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/290300

email: mail@piotrl.net
baseurl: /getting-things-programmed-challange
url: https://piotrl.github.io

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: piotrl
  instagram:
  linkedin: piotr--lewandowski
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: constjs
  stackoverflow: users/2757140/piotr-lewandowski # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Build settings
markdown: kramdown
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
